# Generated by Django 5.1.3 on 2024-11-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='tilecategory',
            options={'verbose_name_plural': 'Tile Categories'},
        ),
    ]
